# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

#goal definition

uint32 goal
uint32[] passing_waypoint_ids  #the follow path must include these passing waypoints
---
#result definition

bool result
uint16 error_code
---
#feedback definition

geometry_msgs/PoseStamped current_pose
uint32 passing_waypoint_id
float32 distance_to_goal