# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

uint8 command
geometry_msgs/PoseStamped goal
nav_msgs/Path path
---
bool result
---
geometry_msgs/PoseStamped current_pose
