# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

uint32 START_SCAN      = 0
uint32 STOP_SCAN       = 1

uint32 cmd_id
---
uint32 SCANNING      = 0
uint32 NAVI_NOT_READY  = 1
uint32 NAVI_ERROR      = 2
uint32 SCAN_STOPPED    = 3

uint32 result
