# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

uint32 ADD_STATION        = 0
uint32 DELETE_STATION     = 1
uint32 ADD_PATH           = 2
uint32 DELETE_PATH        = 3
uint32 QUERY_POSE         = 4
uint32 ADD_FULL_PATH      = 5

uint32 cmd_id
uint32[] stations
float32 x
float32 y
float32 angle
---
bool result
float32 x
float32 y
float32 angle
