# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

#Get the follow path

uint32 goal
uint32 start
bool use_start  #If false, use current base position as start waypoint if current is nearby the waypoint
uint32[] passing_waypoint_ids  #the follow path must include these passing waypoints
---
bool result
uint16 error_code
uint32[] waypoint_id_list
nav_msgs/Path path