# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

uint8 api_id
uint32 waypoint_id
geometry_msgs/Vector3 waypoint
uint32[] adjacent_waypoints
bool bypassing    #If false, AMR will stop when follow path have the obstacle
---
uint32[] waypoint_id_list
uint32 waypoint_id
geometry_msgs/Vector3 waypoint
uint32[] adjacent_waypoints
uint8 result