# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

#Get the P2P path

geometry_msgs/PoseStamped goal
geometry_msgs/PoseStamped start
bool use_start  #If false, use current base position as start point
---
bool result
uint16 error_code
nav_msgs/Path path