# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Emergency mode constants
uint8 ENABLE = 1
uint8 DISABLE = 0

uint8 mode
---
bool result
