# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

std_msgs/Header header
# 0: change mode, 1: moving, 2: rotating
uint8 request_type
float64 rotation_angle
float64 forward_mileage
uint8 change_mode
---
bool result