# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Task ID constants
uint32 REGISTER_NEAREST_OBJECT_DETECTION    = 101
uint32 UNREGISTER_NEAREST_OBJECT_DETECTION  = 102
uint32 REGISTER_IMU_FUSION                  = 201
uint32 UNREGISTER_IMU_FUSION                = 202
uint32 REGISTER_LOCALIZATION_FUSION         = 301
uint32 UNREGISTER_LOCALIZATION_FUSION       = 302
uint32 REGISTER_COLLISION_ALERT             = 401
uint32 UNREGISTER_COLLISION_ALERT           = 402
uint32 REGISTER_ROLLOVER_DETECTION          = 501
uint32 UNREGISTER_ROLLOVER_DETECTION        = 502

uint32 task_id
---
bool success
string err_info
