# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Control mode constants
uint8 APPLICATION = 0
uint8 CHARGER = 1
uint8 REMOTE_CONTROLLER = 2

uint8 mode
---
bool result
