# For playback: "type" (not remandatory if the command "play") and "source" are mandatory.
# For record: "type", "source"(or/and "pub_pcm"), "audio_info.channels", "audio_info.sample_rate",
# and "audio_info.sample_format" are mandatory.

AudioInfo audio_info
# Stream operations (eg. "play", "create", "start", "stop", "release", "mute", "get-buildin-sound")
# "play" command: one touch playback, client doesn't need manage the stream's lifecycle (create/
# start/stop/release), it handle by Audio Service.
string command
# Stream type (eg. "playback", "record")
string type
# Playback or Record path (e.g. "/tmp/clips.wav" or build-in sound name)
string source
# Playback volume [1~100], default is 80
uint8 volume
# -1:repeat, 0:once
int8 repeat
# The handle indicate the stream created by Audio Service when command is "create",
# client controls (eg. start/mute/stop/release) the stream by it.
uint32 stream_handle
# Whether publish pcm data on topic (name is /qrb_audiodata)
# when recording. (true:yes, false:no)
bool pub_pcm
# Need to specify it when requesting the "mute" command.
bool mute
---
bool success
# The handle indicate the stream created by Audio Service when command is "create".
uint32 stream_handle
string[] buildin_sound_name