AudioInfo audio_info
# Stream operations (eg. "play", "create", "start", "stop", "release", "mute", "get-buildin-sound").
# "play": one touch playback, client doesn't need manage the stream's lifecycle (create/
#  start/stop/release), it handle by Audio Service.
string command
# Stream type (eg. "playback", "record")
string type
# Playback or Record path (e.g. "/tmp/clips.wav" or build-in sound name)
string source
# Playback volume [1~100], default is 80
uint8 volume
# -1:repeat, 0:once
int8 repeat
# The handle indicate the stream created by Audio Service when command is "create",
# client controls (eg. start/mute/stop/release) the stream by it.
uint32 stream_handle
# For streaming playback:
#  The streaming audio data subscribes from a topic, it can be specified using topic_name.
# For record:
#  Whether publish pcm data on a topic when recording (true:yes, false:no).
#  The default topic name is "qrb_audiodata", but it can be specified using topic_name.
bool pub_pcm
string topic_name
# Need to specify it when requesting the "mute" command.
bool mute
---
bool success
# The handle indicate the stream created by Audio Service when command is "create".
uint32 stream_handle
string[] buildin_sound_name