# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

qrb_ros_motion_msgs/VelocityLevel velocity
float64 angle
---
bool result
---
geometry_msgs/PoseStamped current_pose