AudioInfo audio_info
# Stream operations (e.g. open, start, stop, close, mute)
string command
uint32 stream_handle
uint32 audio_service_stream_handle
bool need_timestamp
# Playback volume [1~100]
uint8 volume
bool mute
# Repeat play count. -1: unlimited, 0: once
int32 repeat
# Whether publish pcm data on topic when recording. (true:yes, false:no)
# Default topic name is qrb_audiodata,
# client can specify topic name by topic_name.
bool pub_pcm
string topic_name
# Playback or Record path
string file_path
---
uint32 stream_handle
uint32 audio_service_stream_handle
string command
---
float32 timestamp
uint32 stream_handle
