# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

uint8 api_id
uint32 narrow_area_id
float64[8] narrow_area
geometry_msgs/Vector3 point
---
float64[] narrow_area
geometry_msgs/Vector3 point1
geometry_msgs/Vector3 point2
int8 result