# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Motion mode constants
uint8 INACTIVE = 0
uint8 SPEED = 1
uint8 POSITION = 2
uint8 TORQUE = 3

---
uint8 mode
