# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Request
int32 CMD_TEACHING_RECORD = 1
int32 CMD_CONTROLLING_RECORD = 2

int32 manipulator_id
int32 command
uint8 record_id
uint32 sample_rate
---
# Result
bool result
---
# Feedback
builtin_interfaces/Duration elapsed_time