# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Request
int32 manipulator_id
uint8 record_id
---
# Result
bool result
---
# Feedback
builtin_interfaces/Duration elapsed_time