# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Request
int32 manipulator_id
uint8 pose_id
---
# Result
bool result
---
# Feedback
int32 STATE_STARTING = 1
int32 STATE_AMR_ANGLE_ADJUSTING = 2
int32 STATE_AMR_POSITION_ADJUSTING = 3
int32 STATE_ARM_POSE_ADJUSTING = 4
int32 STATE_DONE = 0
int32 STATE_UNREACHABLE = -1
int32 STATE_ERROR = -2

int32 state
builtin_interfaces/Duration elapsed_time