# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# ARM move joint

float64 x
float64 y
float64 z
float64 rx
float64 ry
float64 rz
---
bool result
