uint8 START_STREAM_CASE = 1
uint8 START_FILE_CASE   = 2
uint8 STOP_STREAM_CASE  = 3
uint8 STOP_FILE_CASE    = 4

uint8 action_id
string[] file_path
uint8 camera_id
---
# In the last detection, if the detect result is duplicate, then the contents is empty
string[] contents
string error_info
bool success
---
string[] contents
