# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

int32 ARM_OFFLINE = 0
int32 ARM_CONTROLLING = 1
int32 ARM_TEACHNING = 2

int32 control_mode
---
bool result